# GitHub Pages configuration for AI News Dashboard
title: "AI News Dashboard"
description: "Investment-focused AI news analysis powered by Claude"

# Enable GitHub Pages
github:
  repository_name: ai_news
  repository_url: "https://github.com/HayatoFunahashi/ai_news"

# Plugins
plugins:
  - jekyll-relative-links

# Markdown settings
markdown: kramdown
highlighter: rouge

# Include/exclude files
include:
  - "_*"
  - ".htaccess"
  
exclude:
  - "README.md"
  - "*.py"
  - "*.json"
  - "*.txt"
  - ".env*"
  - "templates/"
  - "tools/"
  - "test_data.json"